version: '3.8'

services:
  mongodb:
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js

  backend:
    build: ./backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
